### ISSUE TITLE
add to site please!

### ISSUE THREAD

**Issue by 17lwinn** [badlydrawnletters/emojifier-docs#20]
- put hamburger icon in bottom right corner, it's covered by the text
- add legal, privacy and licensing info
- an embed which should've shown up has failed to do so, please fix!

**Comment by Techy** [comment]
> an embed which should've shown up has failed to do so, please fix!
 Regarding this, you could try to clear your cache. Let us know if that help!

**Comment by Techy** [comment]
Also could you clarify as to what you mean by "add licensing info", Emojifier isn't open source so what's the need of having licensing info? Regarding the privacy policy, we will add that now.

**Comment by KarateWumpus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add legal and licensing info to docs, fix status alerts](https://trello.com/c/AeYV3VMf/105-add-legal-and-licensing-info-to-docs-fix-status-alerts)
